-- 1. 사용자 테이블
CREATE TABLE IF NOT EXISTS TB_USER (
   USER_SEQ INT(11) NOT NULL AUTO_INCREMENT,
   USER_ID VARCHAR(30) NOT NULL COLLATE 'utf8mb4_general_ci',
   USER_PWD VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   USER_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   USER_AUTH VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   GRP_AUTH VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   EMAIL1 VARCHAR(45) NULL DEFAULT NULL COMMENT '이메일 아이디' COLLATE 'utf8mb4_general_ci',
   EMAIL2 VARCHAR(45) NULL DEFAULT NULL COMMENT '이메일 도메인' COLLATE 'utf8mb4_general_ci',
   USE_YN VARCHAR(1) NULL DEFAULT NULL COMMENT '사용 여부' COLLATE 'utf8mb4_general_ci',
   DEL_YN VARCHAR(1) NULL DEFAULT NULL COMMENT '삭제 여부' COLLATE 'utf8mb4_general_ci',
   LOCK_YN VARCHAR(1) NULL DEFAULT NULL COMMENT '계정 잠금 여부' COLLATE 'utf8mb4_general_ci',
   LOGIN_FAIL_CNT INT(11) NULL DEFAULT NULL COMMENT '로그인 실패 카운트',
   LAST_LOGIN_DT DATETIME NULL DEFAULT NULL COMMENT '마지막 로그인 시간',
   INS_DT DATETIME NULL DEFAULT NULL COMMENT '등록일자',
   INS_IP VARCHAR(20) NULL DEFAULT NULL COMMENT '등록IP' COLLATE 'utf8mb4_general_ci',
   UPD_DT DATETIME NULL DEFAULT NULL COMMENT '수정일자',
   UPD_IP VARCHAR(20) NULL DEFAULT NULL COMMENT '수정IP' COLLATE 'utf8mb4_general_ci',
   PRIMARY KEY (USER_SEQ, USER_ID) USING BTREE,
   INDEX fk_TB_USER_TB_GRP_idx (GRP_AUTH) USING BTREE,
   CONSTRAINT fk_TB_USER_TB_GRP FOREIGN KEY (GRP_AUTH) REFERENCES TB_GRP (GRP_AUTH) ON UPDATE NO ACTION ON DELETE NO ACTION
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB COMMENT='사용자 정보';

-- 2. 그룹 테이블
CREATE TABLE IF NOT EXISTS TB_GRP (
  GRP_AUTH VARCHAR(20) NOT NULL COLLATE 'utf8mb4_general_ci',
  AUTH_NAME VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
  USE_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
  DEL_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
  INS_DT DATETIME NULL DEFAULT NULL,
  INS_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
  INS_USER_SEQ INT(11) NULL DEFAULT NULL,
  UPD_DT DATETIME NULL DEFAULT NULL,
  UPD_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
  UPD_USER_SEQ INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (GRP_AUTH) USING BTREE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB COMMENT='그룹 정보';

-- 3. 메뉴 테이블
CREATE TABLE IF NOT EXISTS TB_MENU (
   MENU_SEQ INT(11) NOT NULL COMMENT '메뉴 시퀀스',
   MENU_CODE VARCHAR(50) NULL DEFAULT NULL COMMENT '메뉴 코드' COLLATE 'utf8mb4_general_ci',
   MENU_TITLE VARCHAR(50) NULL DEFAULT NULL COMMENT '메뉴 이름' COLLATE 'utf8mb4_general_ci',
   MENU_URL VARCHAR(300) NULL DEFAULT NULL COMMENT '메뉴 링크' COLLATE 'utf8mb4_general_ci',
   MENU_PARENT VARCHAR(50) NULL DEFAULT NULL COMMENT '상위 코드' COLLATE 'utf8mb4_general_ci',
   DISP_YN VARCHAR(1) NULL DEFAULT NULL COMMENT '노출 여부' COLLATE 'utf8mb4_general_ci',
   SORT_ORDER INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '정렬 순서',
   USE_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   DEL_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   INS_DT DATETIME NULL DEFAULT NULL,
   INS_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   INS_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   UPD_DT DATETIME NULL DEFAULT NULL,
   UPD_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   UPD_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
   PRIMARY KEY (MENU_SEQ) USING BTREE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB COMMENT='메뉴 관리';

-- 4. 코드 테이블
CREATE TABLE IF NOT EXISTS TB_COMM_CLASS (
    TYPE_CLASS VARCHAR(20) NOT NULL COLLATE 'utf8mb4_general_ci',
    TYPE_DESC VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
    REF_1 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_2 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_3 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_4 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_5 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_6 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_7 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_8 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_9 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_10 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    USE_YN CHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    DEL_YN CHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    SORT_ORDER INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (TYPE_CLASS) USING BTREE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 5. 코드 상세
CREATE TABLE IF NOT EXISTS TB_COMM_CODE (
    TYPE_CLASS VARCHAR(20) NOT NULL COLLATE 'utf8mb4_general_ci',
    TYPE_CODE VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
    CODE_DESC VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
    REF_1 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_2 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_3 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_4 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_5 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_6 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_7 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_8 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_9 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    REF_10 VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    USE_YN CHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    DEL_YN CHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    SORT_ORDER INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (TYPE_CLASS, TYPE_CODE) USING BTREE,
    INDEX fk_TB_COMM_CODE_TB_COMM_CLASS1_idx (TYPE_CLASS) USING BTREE,
    CONSTRAINT fk_TB_COMM_CODE_TB_COMM_CLASS1 FOREIGN KEY (TYPE_CLASS) REFERENCES TB_COMM_CLASS (TYPE_CLASS) ON UPDATE NO ACTION ON DELETE NO ACTION
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 6. 접근 로그 테이블
CREATE TABLE IF NOT EXISTS TB_LOG_ACCESS (
    ACCESS_LOG_SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
    ACCESS_MENU_SEQ INT(11) NULL DEFAULT NULL,
    ACCESS_URI VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_QUERY_STRING TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_FORM_DATA TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_METHOD VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_IP VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_DEVICE VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_BROWSER VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_LANGUAGE VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_OS VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_SESSION_ID VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_REFERRER VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UA_ORIGIN VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    ACCESS_STATUS_CODE VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    RESPONSE_TIME BIGINT(10) NULL DEFAULT NULL,
    INS_DT DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (ACCESS_LOG_SEQ) USING BTREE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 7. 로그인 로그 테이블
CREATE TABLE IF NOT EXISTS TB_LOG_LOGIN (
    LOGIN_LOG_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_SUCCESS VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    STATUS_CODE VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    FAIL_REASON VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_METHOD VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_IP VARCHAR(45) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_DEVICE VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_BROWSER VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_LANGUAGE VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_OS VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_SESSION_ID VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_REFERRER VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    LOGIN_REQ_UA_ORIGIN VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_DT DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (LOGIN_LOG_ID) USING BTREE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 8. 운동 템플릿 테이블
CREATE TABLE IF NOT EXISTS TB_EXER_TPL (
    TPL_SEQ BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    TPL_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    TPL_PHASE VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    SORT_ORDER INT(11) NULL DEFAULT NULL,
    USE_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    DEL_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_DT DATETIME NULL DEFAULT NULL,
    INS_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UPD_DT DATETIME NULL DEFAULT NULL,
    UPD_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UPD_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PRIMARY KEY (TPL_SEQ) USING BTREE,
    INDEX idx_use_del (USE_YN, DEL_YN) USING BTREE,
    INDEX idx_tpl_phase (TPL_PHASE) USING BTREE,
    INDEX idx_sort_order (SORT_ORDER) USING BTREE,
    FULLTEXT INDEX idx_tpl_name (TPL_NAME)
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 9. 운동 테이블
CREATE TABLE IF NOT EXISTS TB_EXER_ATTR (
    TPL_ATTR_SEQ BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    TPL_TYPE_CODE VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    TPL_EXER_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    TPL_CATEGORY_CODE VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    TPL_KIND_CODE VARCHAR(50) NULL DEFAULT NULL COMMENT '운동 성격: 근력 / 유산소 / 스트레칭' COLLATE 'utf8mb4_general_ci',
    TPL_TOTAL_DISTANCE INT(11) NULL DEFAULT NULL COMMENT '수영 전용 총 거리',
    TPL_NOTE TEXT NULL DEFAULT NULL COMMENT '추가 메모 / 설명' COLLATE 'utf8mb4_general_ci',
    TPL_SORT_ORDER INT(11) NULL DEFAULT NULL COMMENT '운동 순서 정렬용',
    USE_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    DEL_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_DT DATETIME NULL DEFAULT NULL,
    INS_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UPD_DT DATETIME NULL DEFAULT NULL,
    UPD_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UPD_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PRIMARY KEY (TPL_ATTR_SEQ) USING BTREE,
    INDEX idx_use_del (USE_YN, DEL_YN) USING BTREE,
    INDEX idx_sort_order (TPL_SORT_ORDER) USING BTREE,
    INDEX idx_exer_kind (TPL_KIND_CODE) USING BTREE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 10. 운동 관계 테이블
CREATE TABLE IF NOT EXISTS TB_EXER (
    TPL_SEQ BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
    TPL_ATTR_SEQ BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
    PRIMARY KEY (TPL_SEQ, TPL_ATTR_SEQ) USING BTREE,
    INDEX fk_TB_EXER_TB_EXER_ATTR1_idx (TPL_ATTR_SEQ) USING BTREE,
    CONSTRAINT FK_TB_EXER_ATTR FOREIGN KEY (TPL_ATTR_SEQ) REFERENCES TB_EXER_ATTR (TPL_ATTR_SEQ) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_TB_EXER_TPL FOREIGN KEY (TPL_SEQ) REFERENCES TB_EXER_TPL (TPL_SEQ) ON UPDATE CASCADE ON DELETE CASCADE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 11. 운동기록 마스터 테이블
CREATE TABLE IF NOT EXISTS TB_PLAN (
    PLAN_SEQ INT(11) NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_TYPE_CODE VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_DATE DATETIME NULL DEFAULT NULL,
    USE_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    DEL_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_DT DATETIME NULL DEFAULT NULL,
    INS_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UPD_DT DATETIME NULL DEFAULT NULL,
    UPD_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UPD_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PRIMARY KEY (PLAN_SEQ) USING BTREE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 12. 운동기록 디테일 테이블
CREATE TABLE IF NOT EXISTS TB_PLAN_DETAIL (
    PLAN_DETAIL_SEQ INT(11) NOT NULL AUTO_INCREMENT,
    PLAN_SEQ INT(11) NOT NULL,
    PLAN_PHASE VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_EXER_NAME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_CATEGORY_CODE VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_KIND_CODE VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_NOTE TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_REPS VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_SETS VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_TIME VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PLAN_TOTAL_DISTANCE INT(11) NULL DEFAULT NULL,
    PLAN_SORT_ORDER INT(11) NULL DEFAULT NULL,
    USE_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    DEL_YN VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_DT DATETIME NULL DEFAULT NULL,
    INS_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    INS_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UPD_DT DATETIME NULL DEFAULT NULL,
    UPD_IP VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UPD_USER_ID VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PRIMARY KEY (PLAN_DETAIL_SEQ) USING BTREE,
    INDEX fk_TB_PLAN_DETAIL_TB_PLAN1_idx (PLAN_SEQ) USING BTREE,
    CONSTRAINT PLAN_FK FOREIGN KEY (PLAN_SEQ) REFERENCES TB_PLAN (PLAN_SEQ) ON UPDATE NO ACTION ON DELETE NO ACTION
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;

-- 13. 공통 코드 조회 함수
DROP FUNCTION IF EXISTS FN_GET_COMM_CODE_DESC;
DELIMITER //
CREATE FUNCTION FN_GET_COMM_CODE_DESC(
	V_IN_TYPE_CLASS VARCHAR(100),
	V_IN_TYPE_CODE VARCHAR(100)
)
RETURNS varchar(500) CHARSET utf8mb4 COLLATE utf8mb4_general_ci
LANGUAGE SQL
DETERMINISTIC
CONTAINS SQL
BEGIN
    DECLARE V_OUT_DESC VARCHAR(500);

    SELECT CD.CODE_DESC
    INTO V_OUT_DESC
    FROM TB_COMM_CLASS CLS
             JOIN TB_COMM_CODE CD
                  ON CLS.TYPE_CLASS = CD.TYPE_CLASS
    WHERE CLS.TYPE_CLASS = V_IN_TYPE_CLASS
      AND CD.TYPE_CODE = V_IN_TYPE_CODE
      AND CLS.USE_YN = 'Y'
      AND CD.USE_YN = 'Y'
        LIMIT 1;

    RETURN V_OUT_DESC;
END //
DELIMITER ;