# Scouter Agent Configuration
obj_name=springbootYeahn-prod
net_collector_ip=${SCOUTER_COLLECTOR_IP}
net_collector_udp_port=6100
net_collector_tcp_port=6100

# SQL 쿼리 파라미터 확인을 위한 설정
profile_sql_escape_enabled=false
profile_connection_open_enabled=true
trace_db_jdbc_allow_full_stacktrace=true
