INSERT INTO TB_GRP (GRP_AUTH, AUTH_NAME, USE_YN, DEL_YN, INS_DT) 
VALUES ('ROLE_USER', '일반사용자', 'Y', 'N', NOW());
INSERT INTO TB_GRP (GRP_AUTH, AUTH_NAME, USE_YN, DEL_YN, INS_DT) 
VALUES ('ROLE_ADMIN', '관리자', 'Y', 'N', NOW());
